// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function AddScriptNoteImages(arg1:string,arg2:Array<bridge.NoteImageInput>):Promise<bridge.NoteDocument>;

export function BootstrapWorkspace():Promise<bridge.WorkspaceSnapshot>;

export function CreateScript(arg1:string):Promise<bridge.ScriptDocument>;

export function DeleteScript(arg1:string):Promise<bridge.WorkspaceSnapshot>;

export function ExportScenePackage(arg1:string):Promise<bridge.PackageTransferResult>;

export function GenerateCodeFromSelection(arg1:bridge.AIGenerationRequest):Promise<bridge.AIGenerationResult>;

export function GetEnvironmentStatus():Promise<bridge.EnvironmentStatus>;

export function GetScriptContent(arg1:string):Promise<bridge.ScriptDocument>;

export function GetScriptList():Promise<Array<string>>;

export function GetScriptNote(arg1:string):Promise<bridge.NoteDocument>;

export function GetSubscriptionStatus(arg1:boolean):Promise<bridge.SubscriptionStatus>;

export function ImportScenePackage():Promise<bridge.ImportSceneResult>;

export function InitializeApp():Promise<bridge.InitSnapshot>;

export function OpenSubscriptionPurchase():Promise<bridge.SubscriptionPurchaseResult>;

export function RebuildRuntime():Promise<bridge.EnvironmentStatus>;

export function RefreshWorkspace(arg1:string):Promise<bridge.WorkspaceSnapshot>;

export function RemoveScriptNoteImage(arg1:string,arg2:string):Promise<bridge.NoteDocument>;

export function RenameScript(arg1:string,arg2:string):Promise<bridge.WorkspaceSnapshot>;

export function SaveAndRun(arg1:string,arg2:string):Promise<void>;

export function SaveScript(arg1:string,arg2:string):Promise<void>;

export function SaveScriptNote(arg1:string,arg2:string):Promise<void>;

export function StopCurrentRun():Promise<bridge.RunControlResult>;
