// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function AddScriptNoteImages(arg1:string,arg2:Array<bridge.NoteImageInput>):Promise<bridge.NoteDocument>;

export function BootstrapWorkspace():Promise<bridge.WorkspaceSnapshot>;

export function CheckForUpdates(arg1:boolean):Promise<bridge.UpdateStatus>;

export function CreateCodeAIVersion(arg1:bridge.CreateCodeAIVersionRequest):Promise<bridge.CodeAIVersion>;

export function CreateScript(arg1:string):Promise<bridge.ScriptDocument>;

export function CreateWorkspace(arg1:string):Promise<bridge.WorkspaceSnapshot>;

export function DeleteCodeAIVersion(arg1:string,arg2:string):Promise<Array<bridge.CodeAIVersion>>;

export function DeleteDesignCard(arg1:string,arg2:string):Promise<void>;

export function DeleteScript(arg1:string):Promise<bridge.WorkspaceSnapshot>;

export function DeleteWorkspace(arg1:string):Promise<bridge.WorkspaceSnapshot>;

export function DownloadUpdate():Promise<bridge.UpdateStatus>;

export function ExportScenePackage(arg1:string):Promise<bridge.PackageTransferResult>;

export function GenerateDesignCardFromSelection(arg1:bridge.AIDesignCardGenerationRequest):Promise<bridge.AIDesignCardResult>;

export function GetAISettings():Promise<bridge.AIProviderSettings>;

export function GetDesignCard(arg1:string,arg2:string):Promise<bridge.DesignCard>;

export function GetEnvironmentStatus():Promise<bridge.EnvironmentStatus>;

export function GetScriptContent(arg1:string):Promise<bridge.ScriptDocument>;

export function GetScriptList():Promise<Array<string>>;

export function GetScriptNote(arg1:string):Promise<bridge.NoteDocument>;

export function GetSubscriptionStatus(arg1:boolean):Promise<bridge.SubscriptionStatus>;

export function GetUpdateStatus():Promise<bridge.UpdateStatus>;

export function ImportScenePackage():Promise<bridge.ImportSceneResult>;

export function ImportScenePackageFromPath(arg1:string):Promise<bridge.ImportSceneResult>;

export function InitializeApp():Promise<bridge.InitSnapshot>;

export function InstallUpdateAndRestart():Promise<void>;

export function ListCodeAIVersions(arg1:string):Promise<Array<bridge.CodeAIVersion>>;

export function ListDesignCardPlacements(arg1:string):Promise<Array<bridge.DesignCardPlacement>>;

export function ListDesignCardVersions(arg1:string,arg2:string):Promise<Array<bridge.DesignCardVersion>>;

export function ListDesignCards(arg1:string):Promise<Array<bridge.DesignCard>>;

export function OpenSubscriptionPurchase():Promise<bridge.SubscriptionPurchaseResult>;

export function OptimizeDesignCard(arg1:bridge.AIDesignCardOptimizeRequest):Promise<bridge.AIDesignCardResult>;

export function RebuildRuntime():Promise<bridge.EnvironmentStatus>;

export function RefreshWorkspace(arg1:string):Promise<bridge.WorkspaceSnapshot>;

export function RemoveScriptNoteImage(arg1:string,arg2:string):Promise<bridge.NoteDocument>;

export function RenameScript(arg1:string,arg2:string):Promise<bridge.WorkspaceSnapshot>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<bridge.WorkspaceSnapshot>;

export function ReorderScripts(arg1:Array<string>,arg2:string):Promise<bridge.WorkspaceSnapshot>;

export function SaveAISettings(arg1:bridge.AIProviderSettings):Promise<bridge.AIProviderSettings>;

export function SaveAndRun(arg1:string,arg2:string):Promise<void>;

export function SaveDesignCardPlacements(arg1:string,arg2:Array<bridge.DesignCardPlacement>):Promise<Array<bridge.DesignCardPlacement>>;

export function SaveScript(arg1:string,arg2:string):Promise<void>;

export function SaveScriptNote(arg1:string,arg2:string):Promise<void>;

export function StartAIWorkflow(arg1:bridge.AIWorkflowRequest):Promise<bridge.AIWorkflowSession>;

export function StopAIWorkflow(arg1:string):Promise<void>;

export function StopCurrentRun():Promise<bridge.RunControlResult>;

export function SwitchWorkspace(arg1:string):Promise<bridge.WorkspaceSnapshot>;

export function UpdateDesignCardPlan(arg1:string,arg2:string,arg3:string):Promise<bridge.DesignCard>;
