import {
  createScript,
  createWorkspace,
  deleteScript,
  deleteWorkspace,
  exportScenePackage,
  exportWorkspacePackage,
  getScriptContent,
  importScenePackage,
  importScenePackageFromPath,
  importWorkspacePackage,
  refreshWorkspace,
  reorderScripts,
  renameScript,
  renameWorkspace,
  saveAndRun,
  saveScript,
  switchWorkspace,
} from "./scriptBridgeCompat";

export function createScriptRepository() {
  return {
    createScript,
    createWorkspace,
    deleteScript,
    deleteWorkspace,
    exportScenePackage,
    exportWorkspacePackage,
    getScriptContent,
    importScenePackage,
    importScenePackageFromPath,
    importWorkspacePackage,
    refreshWorkspace,
    reorderScripts,
    renameScript,
    renameWorkspace,
    saveAndRun,
    saveScript,
    switchWorkspace,
  };
}
